# Generated by Django 5.1.7 on 2025-04-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_conversation', '0002_conversationmessage_feedback_alter_conversation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
